In [63]:
# Import dependicies

import pandas as pd
from sklearn.ensemble import IsolationForest

In [64]:
# Load data

df = pd.read_csv("ai4i2020.csv")
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [65]:
# Input features

X = df[
    [
        "Air temperature [K]",
        "Process temperature [K]",
        "Rotational speed [rpm]",
        "Torque [Nm]",
        "Tool wear [min]"
    ]
]

In [66]:
# Create model

model = IsolationForest(
    n_estimators = 100, # No of Trees
    contamination = 0.02, # Expected % of anomalies
    random_state = 42 # Makes results reproducible
)

In [67]:
# Train model

model.fit(X)

IsolationForest(contamination=0.02, random_state=42)

In [68]:
# Predict anomalies and add prediction to dataframe

df['Prediction'] = model.predict(X)
df['Score'] = model.decision_function(X)

In [ ]:
# Print results

print(df['Prediction'].value_counts())

anomalies = df[df['Prediction'] == -1]
normal = df[df['Prediction'] == 1]

anomalies

        UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6
1         2     L47181    L                298.2                    308.7
2         3     L47182    L                298.1                    308.5
3         4     L47183    L                298.2                    308.6
4         5     L47184    L                298.2                    308.7
...     ...        ...  ...                  ...                      ...
9995   9996     M24855    M                298.8                    308.4
9996   9997     H39410    H                298.9                    308.4
9997   9998     M24857    M                299.0                    308.6
9998   9999     H39412    H                299.0                    308.7
9999  10000     M24859    M                299.0                    308.7

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                       1551         42.8                0                0
1                       1408         46.3                3                0
2                       1498         49.4                5                0
3                       1433         39.5                7                0
4                       1408         40.0                9                0
...                      ...          ...              ...              ...
9995                    1604         29.5               14                0
9996                    1632         31.8               17                0
9997                    1645         33.4               22                0
9998                    1408         48.5               25                0
9999                    1500         40.2               30                0

      TWF  HDF  PWF  OSF  RNF  Prediction     Score
0       0    0    0    0    0           1  0.130227
1       0    0    0    0    0           1  0.131647
2       0    0    0    0    0           1  0.118904
3       0    0    0    0    0           1  0.146485
4       0    0    0    0    0           1  0.139356
...   ...  ...  ...  ...  ...         ...       ...
9995    0    0    0    0    0           1  0.129493
9996    0    0    0    0    0           1  0.137103
9997    0    0    0    0    0           1  0.137513
9998    0    0    0    0    0           1  0.143947
9999    0    0    0    0    0           1  0.178582

[10000 rows x 16 columns]
Prediction
 1    9800
-1     200
Name: count, dtype: int64

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,Prediction,Score
50,51,L47230,L,298.9,309.1,2861,4.6,143,1,0,0,1,0,0,-1,-0.010724
194,195,M15054,M,298.2,308.5,2678,10.7,86,1,0,0,1,0,0,-1,-0.030492
344,345,M15204,M,297.5,308.2,2448,13.8,29,0,0,0,0,0,0,-1,-0.036214
380,381,L47560,L,297.5,308.3,2564,12.8,127,1,0,0,1,0,0,-1,-0.019599
418,419,L47598,L,297.4,308.4,2151,17.7,0,0,0,0,0,0,0,-1,-0.023470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9210,9211,M24070,M,297.9,309.0,2456,13.9,82,0,0,0,0,0,0,-1,-0.000225
9350,9351,L56530,L,298.2,308.7,2186,17.8,31,0,0,0,0,0,0,-1,-0.001369
9406,9407,M24266,M,297.7,308.1,2189,15.6,186,0,0,0,0,0,0,-1,-0.004588
9758,9759,L56938,L,298.6,309.8,2271,16.2,218,1,1,0,0,0,0,-1,-0.036197
9939,9940,H39353,H,298.3,308.1,2636,12.8,84,0,0,0,0,0,0,-1,-0.027386